apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: requestheaderidp
    type: RequestHeader
    requestHeader:
      ca:
        name: request-header-ca
      headers:
      - X-Remote-User
      - SSO-User
      loginURL: "https://${PROXY_ROUTE}/login-proxy/oauth/authorize?${query}"
      challengeURL: "https://${PROXY_ROUTE}/challenging-proxy/oauth/authorize?${query}"
